name: Terraform Deploy EKS

on:
  push:
    branches:
      - main

jobs:
  terraform-eks:
    name: Terraform Apply EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (EKS)
        run: terraform init -migrate-state
        working-directory: Dev/EKS_Cluster_deployment

      - name: Terraform Validate (EKS)
        run: terraform validate
        working-directory: Dev/EKS_Cluster_deployment

      - name: Terraform Plan (EKS)
        run: terraform plan -out=tfplan
        working-directory: Dev/EKS_Cluster_deployment

      - name: Terraform Apply (EKS)
        run: terraform apply -auto-approve tfplan
        working-directory: Dev/EKS_Cluster_deployment
