name: EKS-cluster-deployment

on:
  workflow_dispatch:
  
jobs:
  terraform-backend:
    name: Terraform Apply S3 Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (S3 Backend)
        run: terraform init
        working-directory: Dev/s3-backend

      - name: Terraform Validate (S3 Backend)
        run: terraform validate
        working-directory: Dev/s3-backend

      - name: Terraform Apply (S3 Backend)
        run: terraform apply -auto-approve
        working-directory: Dev/s3-backend
